services:

  mariadb:
    image: bitnami/mariadb:latest
    env_file:
      - mariadb.env
    ports:
      - 3306:3306
    #volumes:
    #  - ./mariadb:/bitnami/mariadb

  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - 8000:8080
    env_file:
      - wp.env
    #volumes:
    #  - ./wordpress/data:/bitnami/wordpress
    depends_on:
      - mariadb

    #nginx
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/app:/app
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/server_block.conf:ro
      - ./nginx/certs/nginx.crt:/opt/bitnami/nginx/conf/bitnami/certs/nginx.crt
      - ./nginx/certs/nginx.key:/opt/bitnami/nginx/conf/bitnami/certs/nginx.key
    depends_on:
      - wordpress
      - mariadb