version: "3.8"

services:
  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - 80:8080
      - 443:8443
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_USERNAME=donda
      - WORDPRESS_PASSWORD=donda
      - WORDPRESS_EMAIL=grdonda@gmail.com
      - WORDPRESS_FIRST_NAME=Giovanni
      - WORDPRESS_LAST_NAME=Donda
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bitnami
    volumes:
      - wordpress_data:/bitnami
    depends_on:
      - mariadb

  # maria db
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=bitnami
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=wordpress
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/bitnami

volumes:
  wordpress_data:
    driver: local
  mariadb_data:
    driver: local
